extern class Error

try {
	throw Error.new()
}