TypeException: The function "foo" is not synchronous (line 3, file "fixtures/compile/await.call.error.var.ks")