TypeException: The function "foo" is not synchronous (line 4, file "fixtures/compile/await.call.error.if.ks")