func foo(bar) ~ Error {
}

func bar() ~ Error {
	foo(42)
}