extern class Error

func foo(bar) ~ Error {
}

foo(42)