extern Error, foo

throw new Error() if foo